# Build react app
FROM node:lts AS build
WORKDIR /app/client

COPY client/package*.json ./
RUN npm install 
COPY client/ .
RUN npm run build

# Serve app
FROM nginx:stable-alpine
COPY --from=build /app/client/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

